### ISSUE TITLE
Enable travis and greenkeeper

### ISSUE THREAD

**Issue by wedgwood** [fastify/fastify-mysql#2]
Hi @mcollina @delvedor, could you enable travis and greenkeeper for the repo.
Thanks :)

**Comment by delvedor** [comment]
Travis enabled, here's the badge:
```
[![Build Status](https://travis-ci.org/fastify/fastify-mysql.svg?branch=master)](https://travis-ci.org/fastify/fastify-mysql)
```

**Comment by delvedor** [comment]
Sure! I'll add you as collaborator :)
Well done!

**Comment by delvedor** [comment]
Done!
https://www.npmjs.com/package/fastify-mysql

But I can't find you in npm :S

**Comment by wedgwood** [comment]
@delvedor [here](https://www.npmjs.com/~wedgwood) is me. thanks :)

**Comment by delvedor** [comment]
I can't add you apparently.
I guess because you are not in the org.

@isaacs I'm sorry to bother you, but I don't know who to ask, so as npm I went to the root :P 

<img width="659" alt="screen shot 2017-11-10 at 07 27 30" src="https://user-images.githubusercontent.com/4865608/32645725-07e67824-c5e9-11e7-906d-816dfb49ea19.png">

**Comment by wedgwood** [comment]
@delvedor Never mind :). You can do it any time later.

**Comment by mcollina** [comment]
@wedgwood I've added you.
